# serverless.yml

service: todos

custom:
  tableName: 'todo-${self:provider.stage}'

provider:
  name: aws
  apiKeys:
    - apiKey-${self:provider.stage}
  usagePlan:
    quota:
      limit: 5000
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["TodoTable", "Arn" ] }
  environment:
    TODO_TABLE: ${self:custom.tableName}

functions:
  create:
    handler: todos/create.create
    events:
      - http:
          path: users/{userId}/todos
          method: post
          private: true
  list:
    handler: todos/list.list
    events:
      - http:
          path: users/{userId}/todos
          method: get
          private: true
  update:
    handler: todos/update.update
    events:
      - http:
          path: users/{userId}/todos/{id}
          method: put
          private: true
  delete:
    handler: todos/delete.delete
    events:
      - http:
          path: users/{userId}/todos/{id}
          method: delete
          private: true
  get:
    handler: todos/get.get
    events:
      - http:
          path: users/{userId}/todos/{id}
          method: get
          private: true

resources:
  Resources:
    TodoTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.TODO_TABLE}

plugins:
  - serverless-aws-documentation
  - serverless-reqvalidator-plugin

