# serverless.yml

service: todos

custom:
  tableName: 'todo-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["TodoTable", "Arn" ] }
  environment:
    TODO_TABLE: ${self:custom.tableName}

functions:
  create:
    handler: todos/create.create
    events:
      - http: 'POST /users/{userId}/todos'
  list:
    handler: todos/list.list
    events:
      - http: 'GET /users/{userId}/todos'
  update:
    handler: todos/update.update
    events:
      - http: 'PUT /users/{userId}/todos/{id}'
  delete:
    handler: todos/delete.delete
    events:
      - http: 'DELETE /users/{userId}/todos/{id}'

resources:
  Resources:
    TodoTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: N
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.TODO_TABLE}

plugins:
  - serverless-aws-documentation
  - serverless-reqvalidator-plugin

